// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4NuBtduGa7diGfKKbFXd_nlqsZS6xDXU',
    appId: '1:50847934766:web:4f150517dbac13c8a7f2bf',
    messagingSenderId: '50847934766',
    projectId: 'form-app-cloud',
    authDomain: 'form-app-cloud.firebaseapp.com',
    storageBucket: 'form-app-cloud.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCByfZmdFKMTZ_Gx_AX_r2jdzhCsq78KB4',
    appId: '1:50847934766:android:e287d4a5fbea3288a7f2bf',
    messagingSenderId: '50847934766',
    projectId: 'form-app-cloud',
    storageBucket: 'form-app-cloud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkehvjZBEtxdV7K3Wcq9v1V1A8dnB925E',
    appId: '1:50847934766:ios:43f5d4cbfe8ad62da7f2bf',
    messagingSenderId: '50847934766',
    projectId: 'form-app-cloud',
    storageBucket: 'form-app-cloud.firebasestorage.app',
    iosBundleId: 'com.example.formapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkehvjZBEtxdV7K3Wcq9v1V1A8dnB925E',
    appId: '1:50847934766:ios:43f5d4cbfe8ad62da7f2bf',
    messagingSenderId: '50847934766',
    projectId: 'form-app-cloud',
    storageBucket: 'form-app-cloud.firebasestorage.app',
    iosBundleId: 'com.example.formapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4NuBtduGa7diGfKKbFXd_nlqsZS6xDXU',
    appId: '1:50847934766:web:5466588b8b32df9ba7f2bf',
    messagingSenderId: '50847934766',
    projectId: 'form-app-cloud',
    authDomain: 'form-app-cloud.firebaseapp.com',
    storageBucket: 'form-app-cloud.firebasestorage.app',
  );
}
